### ISSUE TITLE
Level select cheat not working

### ISSUE THREAD

**Issue by lankv2** [alex-free/sm64gsw#1]
The level select cheat does not work when applied to the rom. i ran ./sm64gsw rom.z64 codes.txt

Inside codes.txt is just the cheat code "A032D58C 0001".

I am using an emulator which is Project 64 3.0.1

My os is Manjaro Linux, i run Project 64 in wine.

**Comment by alex-free** [comment]
Successfully reproduced and fixed the issue in this Linux x86_64 build below:
[sm64gsw.zip](https://github.com/alex-free/sm64gsw/files/11105299/sm64gsw.zip)

This is a regression introduced in v1.4, I'll update SM64GSW shortly with the fix.

**Comment by alex-free** [comment]
> The level select cheat does not work when applied to the rom. i ran ./sm64gsw rom.z64 codes.txt
> 
> Inside codes.txt is just the cheat code "A032D58C 0001".
> 
> I am using an emulator which is Project 64 3.0.1
> 
> My os is Manjaro Linux, i run Project 64 in wine.

Fixed in v2.0. Enjoy!
